version: '3.1'

services:
  config_base:
    image: micro/config-service:0.0.1
    networks:
      - mainnet
    ports:
      - 8888:8888
    environment:
      MICRO_PORT: 8888
      MICRO_DATA_BASE_USER: admin
      MICRO_DATA_BASE_PASSWORD: 12345
      MICRO_DATA_BASE_HOST: 127.0.0.1
      MICRO_DATA_BASE_NAME: spring_cloud
      MICRO_DATA_BASE_ADMIN: admin
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  eureka:
    image: micro/eureka:1.0.0
    networks:
      - mainnet
    ports:
      - 8761:8761
    environment:
      MICRO_CONFIG_URL: config_base
      MICRO_CONFIG_PORT: 8888
      MICRO_DEFUALT_EUREKA_URL: eureka
      MICRO_DEFUALT_EUREKA_PORT: 8761
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    command: sh -c "echo \"run start \" && ./wait-for-it.sh config_base:8888 --timeout=60 && echo \"runnn!!!\" && sleep 100 && echo \"sleep kard\" && java -jar /eureka-service.jar"
networks:
  mainnet:
    external: true