version: '3.1'

services:

  app:
    image:  repository.mirbozorgiarsalan.com/micro/zipkin-service:0.0.1
    networks:
      - mainnet
    ports:
      - 9411:9411
    environment:
      MICRO_PORT: 9411
      MICRO_DATA_BASE_USER: admin
      MICRO_DATA_BASE_PASSWORD: AeA2EJP3DdRaTyGfbm3fkUsss
      MICRO_DATA_BASE_HOST: 45.94.255.110
      MICRO_DATA_BASE_NAME: spring_cloud
      MICRO_DATA_BASE_ADMIN: admin
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == worker ]
    command: sh -c "echo \"sleep kard\" && java -jar /zipkin-service.jar"


networks:
  mainnet:
    external: true









