package mirbozorgi.base.domain.hami;

public enum HamiAndNotificationType {
  BEST_XP_TIME,
  MOST_GEM_BUY,
  BUY,
  FREE_DAILY,
  GIFT_CODE,
  FOLLOW_SOCIAL,
  ADVERTISEMENT,
  DAILY_REWARD,
  REFERRAL,
  MOST_REFERRAL,
  HAMI_ACCEPT,
  HAMI_REJECT,
  FRIEND_REQUEST,
  FRIEND_MESSAGE,
  OTHER
}
