server:
  port: ${MICRO_PORT:8888}



endpoints:
  restart:
    enabled: true


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mirbozorgi-com/Gamification-Microservice-Config-Repo
          default-label: master
          cloneOnStart: true
