version: '3.1'

services:
  accessredis:
    image: redis
    networks:
      - mainnet
    deploy:
      placement:
        constraints: [node.role == manager]
  app:
    image: micro/security-service:0.0.1
    networks:
      - mainnet
    ports:
      - 6074:6074
    environment:
      MICRO_PORT: 6074
      MICRO_DATA_BASE_USER: admin
      MICRO_DATA_BASE_PASSWORD: AeA2EJP3DdRaTyGfbm3fkUsss
      MICRO_DATA_BASE_HOST: 45.94.255.110
      MICRO_DATA_BASE_NAME: spring_cloud
      MICRO_DATA_BASE_ADMIN: admin
      MICRO_CONFIG_URL: 45.94.255.103
      MICRO_CONFIG_PORT: 8888
      MICRO_APP_URL: 45.94.255.103
      MICRO_REDIS_SERVER: accessredis
      MICRO_REDIS_PORT: 6379
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
networks:
  mainnet:
    external: true